@host=https://localhost:7280
# @host=http://localhost:5271

POST {{host}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Juan Carlos",
  "lastName": "Talavan",
  "email": "jctalavan8@gmail.com",
  "password": "mbappe2024"
}